fragment ContentPage on Page {
  primaryRoute {
    id
    path
  }
  name
  # Need to alias this field because the api
  # returns inconsistent field type int / id type
  pageId: id
  content
  images {
    url
  }
  data {
    id
    items {
      type
      properties {
        name
        type
        value {
          ... on StringValue {
            value
          }
        }
      }
    }
  }

  parent {
    id
    name
    primaryRoute {
      id
      path
    }
    subPages(includeHidden: false) {
      ...SubPage
    }
  }

  subPages(includeHidden: false) {
    ...SubPage
  }
}

fragment SubPage on Page {
  id
  name
  primaryRoute {
    id
    path
  }
}
