#import ./ProductPriceFragment.gql
fragment ProductMetadata on Product {
  name
  articleNumber
  description
  ...ProductPrice
  images {
    modifiedDate
    alt
    title
    url
  }
  primaryRoute {
    id
    path
  }
  canonicalCategory {
    name
  }
}
