fragment RouteCrumb on Route {
  id
  path
  slug
  parents {
    id
    path
    slug
    object {
      breadcrumbText
    }
  }
  canonicalPath
  alternateRoutes {
    channelId
    culture
    route
    alias
  }
}
