#import ~/lib/fragments/RouteMetaFragment.gql
#import ~/lib/fragments/HeadFragment.gql
#
#import ./ProductPageFragment.gql

query RouteQuery {
  route(path: "/bikes") {
    ...RouteMeta
    object {
      ...Head
      ...ProductPage
    }
  }
}
